// Generated by CoffeeScript 1.6.3
define(['css!./trapeze.css'], _css, function() {
  var Trapeze;
  Trapeze = function() {
    return this;
  };
  Trapeze.prototype = {
    show: function() {
      return this;
    },
    swing: function() {
      return this;
    },
    hide: function() {
      return this;
    }
  };
  return Trapeze;
});
